name: Daily Weather Notification

on:
  schedule:
    - cron: '0 23 * * *'  # ทุกวันตอน 6 โมงเช้าไทย (UTC+7 = 23 UTC)
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: node index.js

